-- Create hint unlock function specifically for doodle hunt dash games
CREATE OR REPLACE FUNCTION public.unlock_dash_hint_with_token(
  game_uuid UUID,
  guess_id UUID
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  user_uuid UUID;
  current_game RECORD;
  guess_record RECORD;
  current_tokens INTEGER;
  current_hint_used BOOLEAN;
  hint_text TEXT;
BEGIN
  -- Get current user
  user_uuid := auth.uid();
  
  IF user_uuid IS NULL THEN
    RAISE EXCEPTION 'User must be authenticated to unlock hint';
  END IF;

  -- Verify the game exists and belongs to the current user
  SELECT * INTO current_game
  FROM public.doodle_hunt_dash_games
  WHERE id = game_uuid
    AND user_id = user_uuid
    AND status = 'in_progress';
  
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Game not found or not authorized';
  END IF;
  
  -- Get the guess record
  SELECT * INTO guess_record
  FROM public.doodle_hunt_dash_guesses
  WHERE id = guess_id
    AND game_id = game_uuid;
  
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Guess not found';
  END IF;
  
  -- Check if hint is already used
  SELECT hint_used INTO current_hint_used
  FROM public.doodle_hunt_dash_guesses
  WHERE id = guess_id AND game_id = game_uuid;
  
  IF current_hint_used THEN
    RAISE EXCEPTION 'Hint already unlocked for this guess';
  END IF;
  
  -- Get current tokens
  SELECT game_tokens INTO current_tokens
  FROM public.profiles
  WHERE id = user_uuid;
  
  IF current_tokens IS NULL OR current_tokens < 2 THEN
    RAISE EXCEPTION 'Insufficient tokens to unlock hint';
  END IF;
  
  -- Deduct tokens
  UPDATE public.profiles
  SET game_tokens = game_tokens - 2
  WHERE id = user_uuid;
  
  -- Use the existing hint from the guess record (generated by AI)
  hint_text := guess_record.hint;
  
  -- Update the guess to mark hint as used
  UPDATE public.doodle_hunt_dash_guesses
  SET 
    hint_used = TRUE,
    updated_at = NOW()
  WHERE id = guess_id;
  
  -- Return the hint
  RETURN json_build_object(
    'hint', hint_text,
    'success', true
  );
END;
$$;

-- Grant necessary permissions
GRANT EXECUTE ON FUNCTION public.unlock_dash_hint_with_token(UUID, UUID) TO authenticated;
