-- Insert word levels data for Doodle Hunt Dash
INSERT INTO public.wordlevels (word, level, difficulty, category)
VALUES
('cat', 1, 'easy', 'animals'),
('dog', 2, 'easy', 'animals'),
('sun', 3, 'easy', 'nature'),
('house', 4, 'easy', 'objects'),
('tree', 5, 'easy', 'nature'),
('car', 6, 'easy', 'objects'),
('ball', 7, 'easy', 'objects'),
('fish', 8, 'easy', 'animals'),
('flower', 9, 'easy', 'nature'),
('bird', 10, 'easy', 'animals'),

('guitar', 11, 'medium', 'objects'),
('bicycle', 12, 'medium', 'objects'),
('elephant', 13, 'medium', 'animals'),
('castle', 14, 'medium', 'places'),
('mountain', 15, 'medium', 'nature'),
('rocket', 16, 'medium', 'objects'),
('shark', 17, 'medium', 'animals'),
('train', 18, 'medium', 'objects'),
('pencil', 19, 'medium', 'objects'),
('umbrella', 20, 'medium', 'objects'),

('kangaroo', 21, 'medium', 'animals'),
('helicopter', 22, 'medium', 'objects'),
('cactus', 23, 'medium', 'nature'),
('volcano', 24, 'medium', 'nature'),
('lion', 25, 'medium', 'animals'),
('scooter', 26, 'medium', 'objects'),
('bridge', 27, 'medium', 'places'),
('camel', 28, 'medium', 'animals'),
('airplane', 29, 'medium', 'objects'),
('pyramid', 30, 'medium', 'places'),

('octopus', 31, 'hard', 'animals'),
('submarine', 32, 'hard', 'objects'),
('hot air balloon', 33, 'hard', 'objects'),
('koala', 34, 'hard', 'animals'),
('lighthouse', 35, 'hard', 'places'),
('telescope', 36, 'hard', 'objects'),
('jellyfish', 37, 'hard', 'animals'),
('dragon', 38, 'hard', 'mythical'),
('zeppelin', 39, 'hard', 'objects'),
('shrine', 40, 'hard', 'places'),

('triceratops', 41, 'hard', 'animals'),
('sphinx', 42, 'hard', 'places'),
('windmill', 43, 'hard', 'objects'),
('gorilla', 44, 'hard', 'animals'),
('satellite', 45, 'hard', 'objects'),
('pterodactyl', 46, 'hard', 'animals'),
('obelisk', 47, 'hard', 'places'),
('firetruck', 48, 'hard', 'objects'),
('scarecrow', 49, 'hard', 'objects'),
('penguin', 50, 'hard', 'animals');
